# Generated by Django 6.0.1 on 2026-01-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='governed_by',
            field=models.CharField(blank=True, default='المنظومة الذكية (G-Invoice)', max_length=255, null=True),
        ),
    ]
